### ISSUE TITLE
Unhandled exception executing command 'register' in plugin Authy v3.4.2

### ISSUE THREAD

**Issue by wahimp** [Iru21/Authy#44]
Before it was 3.4.0 problem was the same, updated to 3.4.2 problem remained the same.

```java
[12:08:27] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'register' in plugin Authy v3.4.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:874) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:314) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
	at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:298) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1960) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
	at net.minecraft.server.network.PlayerConnection.lambda$18(PlayerConnection.java:1922) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
	at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1152) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
	at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
	at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1131) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1124) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
	at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
	at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1108) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1019) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3822-Spigot-9ebce8a-b60a95c]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (database is locked)
	at org.sqlite.core.DB.newSQLException(DB.java:1179) ~[sqlite-jdbc-3.42.0.0.jar:?]
	at org.sqlite.core.DB.newSQLException(DB.java:1190) ~[sqlite-jdbc-3.42.0.0.jar:?]
	at org.sqlite.core.DB.execute(DB.java:985) ~[sqlite-jdbc-3.42.0.0.jar:?]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$execute$0(JDBC3PreparedStatement.java:57) ~[sqlite-jdbc-3.42.0.0.jar:?]
	at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454) ~[sqlite-jdbc-3.42.0.0.jar:?]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:52) ~[sqlite-jdbc-3.42.0.0.jar:?]
	at me.iru.data.DatabaseConnection.query(DatabaseConnection.kt:75) ~[?:?]
	at me.iru.data.PlayerData.update(PlayerData.kt:89) ~[?:?]
	at me.iru.data.PlayerData.create(PlayerData.kt:36) ~[?:?]
	at me.iru.AuthManager.register(AuthManager.kt:19) ~[?:?]
	at me.iru.commands.cRegister.onCommand(cRegister.kt:51) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	... 23 more

```

**Comment by Iru21** [comment]
corrupted database, try restoring a backup
